name: Test global env works

on:
  workflow_dispatch:
  
env:
  SOME_SECRET: 'Not a secret, lazy to rename...'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Print raw varibles file
      run: | 
        echo "Raw variables file"
        cat variables.txt
  
    - name: Replace variables
      uses: mertoguz/variable-replace/parent-env-test@main
      with:
        fileName: 'variables.txt'
        
    - name: Print varibles file after variables replacement
      run: | 
        echo "Variables file after replacement"
        cat variables.txt
